### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by ben-ronell** [HoshiaiP/EEP153Proj3B#1]
Great code overall, I think a little bit of feedback would be to fix a couple of the spelling errors and maybe add some commenting to explain a little bit more about the code, it was confusing. Also, it might be helpful to facet wrap the graphs so instead of having 3 or 4 large separate graphs, you can have them close together and be able to show key differences, just a thought. Overall, good analysis though.

**Comment by hoshiaip** [comment]
Thanks for your comment.
It is true that our notebook need titles, headers, and texts to better explain what is happening behind the scene. It can be confusing to someone who's not familiar with the data structure of the survey we are using. 
Also, I see your point about presenting the graphs in a block. The reason we didn't do that is that we will only select two graphs to present, and the rest is just for our own reference.
