### ISSUE TITLE
Code Review by Team Balisacan

### ISSUE THREAD

**Issue by lizchoi0918** [HoshiaiP/EEP153Proj3B#2]
The code looks great overall, I think you could comment/provide a header for us to better understand what you are trying to show us. I enjoyed looking at the log production of specific food product and its consumption rate.  More specifically, I think I understand the last section of your code with predicted quantities because we are analyzing the same data set (Bukiddnon, Phillippines) but it's difficult to know without details regarding what q hat entails.

**Comment by hoshiaip** [comment]
Hi, thank you for your comment,
Our notebook could definitely use some more titles, headers, and explanatory texts, especially for the benefit of those who are not familiar with the dataset both of our groups are using. Thank you for the advice!
